### ISSUE TITLE
add ability to manually enter a depth/time range

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stoqs/stoqs#33]
```
What steps will reproduce the problem?
1. click & drag to select a time/depth range in the upper right panel

What is the expected output? What do you see instead?
The temporal and depth range are displayed on top but cannot be modified. This 
would be especially useful if one wanted a slightly bigger view (e.g. selected 
0-90m as depth range but want to see down to 100m after all) since currently 
you need to totally clear the depth/time selection and start over.

What version of the product are you using? On what operating system?
chrome & linux

Please provide any additional information below.


```

Original issue reported on code.google.com by `monique....@gmail.com` on 22 Jan 2014 at 4:36

**Comment by MBARIMike** [comment]
The right-click functionality should have been fixed by https://github.com/stoqs/stoqs/pull/270.

**Comment by MBARIMike** [comment]
Hello @messiem, 

The right-click/zoom-out function should be working better now. Please let us know if this is still an issue.

Also, rather than cluttering up the web UI with a lot of functionality such as type-in depth and time fields I'd like to steer people to using Jupyter Noteboooks for custom queries of STOQS databases. Other thoughts/suggestions welcomed!

-Mike
