### ISSUE TITLE
Modernize the installation and setup procedures

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stoqs/stoqs#57]
```
What steps will reproduce the problem?
1. Follow the instructions in the PREREQUISITES and INSTALL files
2. This can take an experiences sysadmin the better part of a day to complete
3. Modern packaging and deployment tools can make this easier

See the answer for using a Makefile and vagrant from D.Shawley at:

http://stackoverflow.com/questions/18270859/do-i-need-to-use-virtualenv-with-vag
rant



```

Original issue reported on code.google.com by `MBARIm...@gmail.com` on 1 Jan 2015 at 8:42

**Comment by MBARIMike** [comment]
The team is making progress: https://github.com/jergutierrez/stoqs/commit/28710a3d8d5423c24b649fb26b269ba8faa905ed

**Comment by MBARIMike** [comment]
Merged https://github.com/stoqs/stoqs/pull/74, pulled into a fresh clone on MacOS, executed:

    vagrant plugin uninstall vagrant-vbguest
    vagrant up --provider virtualbox

Exploring the system after a 'vagrant ssh' shows that postgres is running with the postgis database installed. Great work!

The next steps are to follow instructions in INSTALL to create a default stoqs database, load the test data, and start the development server so that the user can see their very own STOQS User Interface in action. Perhaps these steps can be added to the Vagrantfile or they can be put into another script. I'm not sure what's best.

**Comment by MBARIMike** [comment]
Refining the Vagrantfile to work in the django17upgrade branch. See https://github.com/MBARIMike/stoqs/blob/django17upgrade/README.md. Would be nice to add code to provision.sh for ubuntu apt-get commands so that continuous integration testing can occur on travis-ci.org...

**Comment by MBARIMike** [comment]
Succeeded in getting a travis-ci build to pass through the test stoqs database load step: https://travis-ci.org/MBARIMike/stoqs/builds/59070768! Not using provision.sh, but instead putting only what's needed in .travis.yml and relying on standard travis-ci provisioning for the prerequisites.

**Comment by stoqs** [comment]
A huge thank you to the CSUMB CSIT capstone project students @mamparo, @jergutierrez, @justkeating, and @Brett-Rankin for figuring out Vagrant and the bash scripting to complete this project. This will be a great help for future capstone students who will easily be able to boot up a development environment for working on other Issues of the STOQS project.
