### ISSUE TITLE
Implement a loader for Doarado LOPC data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stoqs/stoqs#61]
```
Data from the Laser Optical Plankton Counter instrument on the MBARI Dorado AUV 
are routinely processed into NetCDF files. These data need to be loaded into 
STOQS database and used for assessing the size distributions of particles. 

An example such data set is here:

http://dods.mbari.org/opendap/data/ssdsdata/ssds/generated/netcdf/files/ssds.sho
re.mbari.org/auvctd/missionlogs/2014/2014295/2014.295.00/lopc.nc.html

The sepCountList and mepCountList variables are spatial-temporal trajectories 
of a spectrum of counts in size classes ranging from 0.1 to 15 mm.

In order to produce counts from the Multi Element Plankton an integration over 
time must be done. The default integration period is 10 seconds. Ideally, we 
would like to have the LOPC data line up with the 2 second data that we 
currently load from the other Dorado instruments. There is also the issue of 
the fourth dimension of "bin" and how that can fit into the STOQS data model. 
There are 2 big issues to resolve:

1. Temporal matching of the LOPC to other data. Note that 10 seconds may not be 
the optimal integration time. Whatever scheme designed must accommodate 
variable integration time periods

2. Storing the whole size class spectrum. There are 994 bins. Should each be a 
different parameter name? Is a schema change needed?

Parallel development of Machine Learning techniques may help us evaluate the 
best approaches for these issues.

```

Original issue reported on code.google.com by `MBARIm...@gmail.com` on 11 Feb 2015 at 12:09

**Comment by MBARIMike** [comment]
As work on Issue #44 is nearing completion I'm considering a schema change that helps address issue 2 above. It would be a new association table named something like MeasuredParameterArray that would have an ArrayField (https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/) for storing the spectra. I think some additional fields are needed somewhere in the model to store the domain information. @danellecline, do you have any thoughts on this?

**Comment by danellecline** [comment]
If a bin represents a size class range, that should be captured in metadata somewhere since that would be needed for machine learning or other types of analysis. I don't think a name is appropriate for each bin, an array is fine.  

I haven't worked with this type of data before so I'm a little unclear on what impact the schema changes would have.  How is the LOPC  data routinely used with the other science data ? Are other sampling methods going to be compared to this and how will they be spatially-temporally aligned ?  

Help me understand something. It seems like the LOPC is conceptually similar to the net tow data that we have a loader for. @MBARIMike, why can't it be loaded using the existing schema ?

**Comment by MBARIMike** [comment]
LOPC data is similar to net tow data in that it can be an integrative measurement, but that's the limit of its similarity. LOPC data is collected in concert with other MeasuredParameters so we have an opportunity to relate it with those data with a good schema evolution. We need a schema change because currently MeasuredParameter contains one scalar field: `datavalue`. Initially I was thinking that another table (MeasuredParameterArray) holding a `dataarray` field would be an efficient way to model the storage of LOPC's 'vector' data. However, that would require an additional association table (MeasuredParameterArrayResource) to support labeling data, complicating work in other areas of STOQS.

Perhaps we can simply add a `dataarray` ArrayField to MeasuredParameter and a `domain` ArrayField to Parameter to enable storage of data from instruments that produce lists of values...

**Comment by MBARIMike** [comment]
A little testing shows that adding a `dataarray` ArrayField to MeasuredParameter does not increase the size of a database when all of its values are null. Therefore this approach seems like a good one.

**Comment by MBARIMike** [comment]
This [Jupyter Notebook](https://github.com/stoqs/stoqs/blob/master/stoqs/contrib/notebooks/summarize_LOPC.ipynb) demonstrates the ability to load LOPC data.
